[package]
name = "encryption"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "encryption"
crate-type = ["cdylib", "rlib"]

[dependencies]
zeroize = "1.6"
rand = "0.8"
pyo3 = "0.19" 

[build-dependencies]
cc = "1.0"

[dev-dependencies]
dudect-bencher = "0.5"
clap = "2"
rand = "0.8"
