name: chacha

defaults:
  run:
    working-directory: chacha

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-avx2:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@master
      - run: cargo test -- -C target-feature=+avx2

  test-fallback:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@master
        toolchain: stable
        targets: aarch64-unknown-linux-gnu
      - run: cargo test
