name: chacha

defaults:
  run:
    working-directory: chacha

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@nightly

      - run: cargo test
