name: chacha

defaults:
  run:
    working-directory: chacha

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
        target: [x86_64, x86, aarch64, armv7, s390x, ppc64le]
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - run: ${{ matrix.deps }}

      - run: cargo test --target ${{ matrix.target }}
