name: chacha
on: [push, pull_request]

defaults:
  run:
    working-directory: ./chacha

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test
